### ISSUE TITLE
[tcp] Receive Old and New Data on Retransmissions

### ISSUE THREAD

**Issue by ppenna** [demikernel/inetstack#102]
Description
========

In `protocols::tcp::established::ControlBlock::receive_data()` we could receive both old and new data when receiving a new segment that contains duplicate data.

**Comment by BrianZill** [comment]
After PR #123, we trim off any old (i.e. already ACK'd) data from incoming segments before passing the segment to receive_data().  While this is helpful, it doesn't completely solve the problem.

receive_data() still needs to be able to add potentially over-lapping segments to the out-of-order queue without duplicating data.  This part still needs to be fixed.

**Comment by BrianZill** [comment]
I fixed this in PR #145.
