### ISSUE TITLE
[ip] Allow non-zero IP identification field when DF flag is set

### ISSUE THREAD

**Issue by HelloKayT** [demikernel/inetstack#162]
Description
-------------

Currently, it seems that packets with a non-zero IP identification field are not processed. You can observe this by running the UDP ping-pong test where one side is using catnip and the other side is using the Linux kernel network stack. The catnip side will never receive any packets. The DF flag is always set on the packets from the Linux kernel, and if you rewrite the IP packet ID field using nftables on the Linux kernel side to always be 0, then the UDP ping-pong test does pass. I think according to [RFC 6864](https://www.rfc-editor.org/rfc/rfc6864#section-4) that if the DF flag is set, then the ID field in the IP header can be set to any arbitrary value.

I believe it's probably due to this check, but I haven't tried removing it: https://github.com/demikernel/inetstack/blob/e0e375056c73d308437757a1e24503349a1a4032/src/protocols/ipv4/datagram.rs#L176

**Comment by BrianZill** [comment]
@HelloKayT is correct about that line in datagram.rs.  It is clearly wrong in checking the value of the identification field.  Not only is the identification (id) field _allowed_ to be non-zero, it is _required_ to be a (temporally) unique value (i.e. non-zero) in every IPv4 datagram that doesn't have the DF flag bit set.  And there is nothing in the specification requiring it to be anything in particular if the DF flag bit _is_ set.

As @HelloKayT notes, this breaks interoperability with practically every other IP stack out there.

**Comment by BrianZill** [comment]
Fixed by PR #184.
