### ISSUE TITLE
[udp] UDP Will Fail to Receive Datagrams Without a Checksum

### ISSUE THREAD

**Issue by BrianZill** [demikernel/inetstack#175]
Description
========

UDP datagrams may contain a checksum, which is supposed to be optional.  A zero value in the checksum field is supposed to indicate that the datagram doesn't have a valid checksum, and thus the receiver shouldn't check it.

Our implementation, however, when in software checksum mode, will always attempt to verify the checksum.  This verification will fail roughly 2^16 - 2 out of 2^16 - 1 times, resulting in almost guaranteed packet loss.

Expected Behavior
============

The stack shouldn't attempt to verify the checksum of a UDP datagram if a valid (i.e., non-zero) checksum value isn't present.

**Comment by ppenna** [comment]
I confirm this bug. As @BrianZill mentioned the stack attempts to verify the checksum of a UDP datagram that has a zero value in this field, when running checksum in software:

https://github.com/demikernel/inetstack/blob/ba498ee68816058212fa1e9d50296496a42eb981/src/protocols/udp/datagram/header.rs#L92-L99
