### ISSUE TITLE
[inetstack] Constructors should Fail Instead of Panicking

### ISSUE THREAD

**Issue by ppenna** [demikernel/inetstack#191]
Description
-------------

Currently, constructors of the following components are panicking on errors:

- [x] [`Peer`](https://github.com/demikernel/inetstack/blob/df4f2c2487870a381aff330f33d8fbf7fbaf56f3/src/protocols/peer.rs#L39)
- [x] [`Icmpv4Peer`](https://github.com/demikernel/inetstack/blob/df4f2c2487870a381aff330f33d8fbf7fbaf56f3/src/protocols/icmpv4/peer.rs#L130)
- [x] [`UdpPeer`](https://github.com/demikernel/inetstack/blob/df4f2c2487870a381aff330f33d8fbf7fbaf56f3/src/protocols/udp/peer.rs#L114)
- [x] [`TcpPeer`](https://github.com/demikernel/inetstack/blob/df4f2c2487870a381aff330f33d8fbf7fbaf56f3/src/protocols/tcp/peer.rs#L127)

Expected Behavior
------------------

Instead of panicking, all these constructors should return a `Result<Fail, T>` instead.

**Comment by justinvzyl** [comment]
Under what conditions have you found the `::new` trait to panic for these?

**Comment by ppenna** [comment]
Hello @justinvzyl.

Thanks for the message.

This issue was created before commit `df4f2c2487870a381aff330f33d8fbf7fbaf56f3` was merged into `dev`. I've updated the pointers to be clearer about this issue.

In summary we have the following panicking:
- ICMPv4: https://github.com/demikernel/inetstack/blob/df4f2c2487870a381aff330f33d8fbf7fbaf56f3/src/protocols/icmpv4/peer.rs#L142
- UDP: https://github.com/demikernel/inetstack/blob/df4f2c2487870a381aff330f33d8fbf7fbaf56f3/src/protocols/udp/peer.rs#L137

Thus, these should be updated:
- https://github.com/demikernel/inetstack/blob/df4f2c2487870a381aff330f33d8fbf7fbaf56f3/src/protocols/peer.rs#L40
- https://github.com/demikernel/inetstack/blob/df4f2c2487870a381aff330f33d8fbf7fbaf56f3/src/protocols/peer.rs#L44
- https://github.com/demikernel/inetstack/blob/df4f2c2487870a381aff330f33d8fbf7fbaf56f3/src/protocols/tcp/peer.rs#L127

TCP does not panic currently panic, but with the ongoing refactor on the TCP stack it is likely that it will, and it is better to fix this now rather than revisiting this issue afterwards.

Cheers

**Comment by justinvzyl** [comment]
@ppenna, thanks for the clarification. I'd be happy to take on this small task in the next day or two.

**Comment by ppenna** [comment]
> @ppenna, thanks for the clarification. I'd be happy to take on this small task in the next day or two.

You are welcome :)

Sounds great! Please remember to have `dev` as your base branch, and when submitting a PR, use it as the base one as well.
